// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvptnidlblqvygjzilbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2cHRuaWRsYmxxdnlnanppbGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjgxNDUsImV4cCI6MjA2MzgwNDE0NX0.D0nEzMgyWJTiqt2FCcszw_JFi_JBpvd8TpoTAcpEv-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);